# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundTrivialNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi_key',
            field=models.CharField(max_length=27, unique=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AddField(
            model_name='compoundtrivialnames',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compound_db.Compound'),
        ),
    ]
