# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0004_auto_20160409_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemblbioassaydata',
            name='bioactivity_type',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
