# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0005_auto_20160409_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemblbioassaydata',
            name='units',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
