# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0006_auto_20160409_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemblbioassaydata',
            name='assay_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='chemblbioassaydata',
            name='bioactivity_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='chemblbioassaydata',
            name='ingredient_cmpd_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='chemblbioassaydata',
            name='operator',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='chemblbioassaydata',
            name='units',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
