# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 09:47
from __future__ import unicode_literals

from django.db import migrations
from django_rdkit.operations import GiSTIndex


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0010_auto_20160415_0942'),
    ]

    operations = [
        GiSTIndex('Compound', 'mfp2')
    ]
