# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 11:15
from __future__ import unicode_literals

import django_rdkit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0002_auto_20160314_2022'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS rdkit;'),
        migrations.AddField(
            model_name='compound',
            name='mol',
            field=django_rdkit.models.fields.MolField(default=None),
            preserve_default=False,
        ),
    ]
