# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0003_compound_mol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChEMBLBioassayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_id', models.CharField(blank=True, max_length=16)),
                ('ingredient_cmpd_id', models.CharField(blank=True, max_length=16)),
                ('units', models.CharField(blank=True, max_length=8)),
                ('bioactivity_type', models.CharField(blank=True, max_length=8)),
                ('value', models.FloatField(null=True)),
                ('operator', models.CharField(blank=True, max_length=4)),
                ('activity_comment', models.CharField(blank=True, max_length=64)),
                ('target_confidence', models.IntegerField(null=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compound_db.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLTargetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=13, unique=True)),
                ('uniprot_accession', models.CharField(max_length=6)),
                ('chembl_id', models.CharField(max_length=16)),
                ('organism', models.CharField(max_length=128)),
                ('preffered_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='chemblbioassaydata',
            name='target_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compound_db.ChEMBLTargetData'),
        ),
    ]
