# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0008_auto_20160409_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.CharField(max_length=4096, unique=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
