# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 09:42
from __future__ import unicode_literals

import django_rdkit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compound_db', '0009_auto_20160409_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemblbioassaydata',
            options={'verbose_name': 'ChEMBL Bioassay Data', 'verbose_name_plural': 'ChEMBL Bioassay Data'},
        ),
        migrations.AlterModelOptions(
            name='chembltargetdata',
            options={'verbose_name': 'ChEMBL Target Data', 'verbose_name_plural': 'ChEMBL Target Data'},
        ),
        migrations.AddField(
            model_name='compound',
            name='ffp2',
            field=django_rdkit.models.fields.BfpField(null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='mfp2',
            field=django_rdkit.models.fields.BfpField(null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='torsionbv',
            field=django_rdkit.models.fields.BfpField(null=True),
        ),
    ]
